### ISSUE TITLE
Adapter turns yellow after first polling

### ISSUE THREAD

**Issue by MegaMatze** [marvingrieger/ioBroker.haassohn#41]
Peletto 434 Grande is used. Does poll data correctly first time but then the adapter turns yellow in ioBroker and data is not updated anylonger. Restarting adapter works for first polling and then turns yellow again. Is the 30 second polling intervall too much for the Haas Sohn Cloud?

**Comment by marvingrieger** [comment]
Hey,

since this is an oven, I configured the adapter to terminate itself if an unknown (=untested) hardware/software version is present. However, each new combination can be unlocked.

If you take a look at the log, you should see something like

`Hardware / Software combination (???) is not supported by this adapter! Please open an issue on GitHub.
`

Can you send me this line please?

Best regards

**Comment by MegaMatze** [comment]
Yep it's true. That's what the log shows

Hardware / Software combination (KS01_V7.11) is not supported by this adapter! Please open an issue on GitHub.

**Comment by marvingrieger** [comment]
Thanks, I unlocked your device in Version 1.0.5.
Please install this version directly from GitHub, using the "Expert Mode" in ioBroker:

<img width="1005" alt="Bildschirmfoto 2021-11-12 um 21 00 32" src="https://user-images.githubusercontent.com/1997765/141527729-c5005f8d-7887-4796-a7ff-5075be622250.png">

If you can confirm that it works as expected, I'll add it to the stable list.

**Comment by MegaMatze** [comment]
Thanks for the Update. Sorry for the late reply-was on vacation! Adapter works great now. Thanks!
