### ISSUE TITLE
Software combination (KS01_V7.01) is not supported by this adapter!

### ISSUE THREAD

**Issue by hjzer** [marvingrieger/ioBroker.haassohn#59]
Hi Marvin,
thanks for the adapter.
The adapter runs on my system a few seconds and i become the fallowing message in log.

haassohn.0 (954) Hardware / Software combination (KS01_V7.01) is not supported by this adapter! Please open an issue on GitHub.
2024-01-04 16:34:50.136  - [31merror[39m: haassohn.0 (954) Some critical error occurred (see log). Disabling the adapter 

My System:
HSP 2.17 PREMIUM (V7.01)
Adapter v1.0.9

Thanks in advance for your help.

**Comment by marvingrieger** [comment]
Hey,
the device you are using has been added in v1.0.11. Since this version is not published yet, please install the adapter directly from GitHub:

<img width="993" alt="Bildschirmfoto 2021-12-20 um 20 47 57" src="https://user-images.githubusercontent.com/1997765/146824402-27f1d7e5-e549-4af3-a0ea-bca007ae38ec.png">

Best regards

**Comment by hjzer** [comment]
Hallo Marvin,
Habe den Adapter installiert und er läuft jetzt.
Vielen Dank
